import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import { Container, ProductDetailsContainer, ResultsContainer } from "../../../src/styles/Pages/relatedDetailsStyle";
import { useEffect, useState } from "react";
import useMediaQuery from "../../../src/hooks/useMediaQuery";
import { Paginate, TitlePage } from "../../../src/atoms";
import Router, { useRouter } from "next/router";
import { langConverter, parseContext, pTypeConverter, tmdbApiKey } from "../../../src/js/utility";
import Tabs from "../../../src/atoms/Tabs";
import { Card } from "../../../src/components";

const creditTabsList = [
	{
		id: 'cast',
		label: 'Cast',
		icon: null
	},
	{
		id: 'troupe',
		label: 'Troupe',
		icon: null
	}
]

export async function getServerSideProps(context) {
  try {
    const query = parseContext(context.query);
    const resolvedUrl = parseContext(context.resolvedUrl).split('/')[1]
    const resRelated = await fetch(`https://api.themoviedb.org/3/${resolvedUrl}/${query.id}/recommendations?api_key=${tmdbApiKey}`);
    const relatedDetails = await resRelated.json();
    const resProductDetails = await fetch(`https://api.themoviedb.org/3/${resolvedUrl}/${query.id}/credits?api_key=${tmdbApiKey}`);
    const productDetails = await resProductDetails.json();
    return {
      props: {
        relatedDetails,
        productDetails,
        productTypeContext: resolvedUrl,
        query
      },
    };
  } catch (err) {
    console.error(err);
    return {
      props: {
        err: "Something went wrong",
      },
    };
  }
}

export default function RelatedDetailsMovie({relatedDetails, productDetails, productTypeContext, query}) {
  const tabs = creditTabsList;
  const router = useRouter();
  const dispatch = useDispatch();
  
  const { slug, id: pid } = router.query;
  const [relatedDetailsState, setRelatedDetailsState] = useState({});
  const [productDetailsState, setProductDetailsState] = useState({});
  const [pageSelected, setPageSelected] = useState(1);
  const [activeTab, setActiveTab] = useState(tabs[0]);
  const user = useSelector((state) => state.userData);
  const userLanguageState = useSelector((state) => state.userData.language);

  const isTablet = useMediaQuery(769);
  const isMobile = !useMediaQuery(426);

  useEffect(() => {
    setRelatedDetailsState(relatedDetails);
  }, [relatedDetails]);

  const getDetailsProduct = async () => {

    if (userLanguageState && relatedDetails) {
      const details = await fetch(
        `https://api.themoviedb.org/3/${productTypeContext}/${query.id}?api_key=${tmdbApiKey}&language=${langConverter(userLanguageState)}`
        ).then(res => res.json());

      const related = await fetch(
        `https://api.themoviedb.org/3/${productTypeContext}/${query.id}/recommendations?api_key=${tmdbApiKey}&page=${pageSelected}`
        ).then(res => res.json());

      
      setRelatedDetailsState(related);
      setProductDetailsState(details);
    }
  };

  useEffect(() => {
    getDetailsProduct();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userLanguageState, relatedDetails, productDetails, pageSelected]);

  const onChangeTab = tab => {
    setActiveTab(tab);
  };

  const handleOnChangePage = (e, page) => {
    setPageSelected(page);
	}

  return (
    <ProductDetailsContainer>
      <Head>
        <title>Related {productDetailsState?.title}  | Aperifilm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#e30000" />
        <meta name="msapplication-TileColor" content="#ffc40d" />
        <meta name="theme-color" content="#ffffff"></meta>
      </Head>

      <TitlePage primaryTitle="pageTitleRelated" title={productDetailsState?.title} hasBackButton />

      <ResultsContainer>
        {
            <>
              {relatedDetailsState?.results?.map((item, index) => (
                <Card key={index} product={item} productType={productTypeContext === 'movie' ? 'productTypeFilm' : 'productTypeTvSeries'} className="card" role={item?.job || item?.department} />
              ))}
            </>
        }
      </ResultsContainer>
      {relatedDetailsState.total_pages > 1 && (
        <Paginate onChange={(e, page) => handleOnChangePage(e, page)} totalPages={relatedDetailsState?.total_pages} />
      )}
    </ProductDetailsContainer>
  );
}
