export const GET_USERS_LIST = 'GET_USERS_LIST';
export const USERS_ERROR = 'USERS_ERROR';

// User
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_TRANSLATE = 'SET_TRANSLATE';
export const SET_USER_DATA_FROM_LOGIN = 'SET_USER_DATA_FROM_LOGIN';
export const SET_USER_LIST_PRODUCTS = 'SET_USER_LIST_PRODUCTS';