export const USERS_ERROR = 'USERS_ERROR';

// App
export const SET_FULLSCREEN_PANEL = 'SET_FULLSCREEN_PANEL';
export const SET_FULLSCREEN_PANEL_ERROR = 'SET_FULLSCREEN_PANEL_ERROR';

export const SET_MODAL_VOTE = 'SET_MODAL_VOTE';
export const SET_MODAL_VOTE_ERROR = 'SET_MODAL_VOTE_ERROR';

export const SET_MODAL_EXPERIENCE = 'SET_MODAL_EXPERIENCE';
export const SET_MODAL_EXPERIENCE_ERROR = 'SET_MODAL_EXPERIENCE_ERROR';

export const SET_MODAL_DELETE = 'SET_MODAL_DELETE';
export const SET_MODAL_DELETE_ERROR = 'SET_MODAL_DELETE_ERROR';

export const SET_MODAL_SHARE = 'SET_MODAL_SHARE';
export const SET_MODAL_SHARE_ERROR = 'SET_MODAL_SHARE_ERROR';

// User
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_LANGUAGE_ERROR = 'SET_LANGUAGE_ERROR';

export const SET_USER_DATA_FROM_LOGIN = 'SET_USER_DATA_FROM_LOGIN';
export const SET_USER_DATA_FROM_LOGIN_ERROR = 'SET_USER_DATA_FROM_LOGIN_ERROR';

export const SET_USER_LIST_PRODUCTS = 'SET_USER_LIST_PRODUCTS';
export const SET_USER_LIST_PRODUCTS_ERROR = 'SET_USER_LIST_PRODUCTS_ERROR';


// PRODUCT
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';