export const GET_USERS_LIST = 'GET_USERS_LIST';
export const GET_USERS_LIST_ERROR = 'GET_USERS_LIST_ERROR';
export const USERS_ERROR = 'USERS_ERROR';

// App
export const SET_FULLSCREEN_PANEL = 'SET_FULLSCREEN_PANEL';
export const SET_FULLSCREEN_PANEL_ERROR = 'SET_FULLSCREEN_PANEL_ERROR';

// User
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_LANGUAGE_ERROR = 'SET_LANGUAGE_ERROR';

export const SET_TRANSLATE = 'SET_TRANSLATE';
export const SET_TRANSLATE_ERROR = 'SET_TRANSLATE_ERROR';

export const SET_USER_DATA_FROM_LOGIN = 'SET_USER_DATA_FROM_LOGIN';
export const SET_USER_DATA_FROM_LOGIN_ERROR = 'SET_USER_DATA_FROM_LOGIN_ERROR';

export const SET_USER_LIST_PRODUCTS = 'SET_USER_LIST_PRODUCTS';
export const SET_USER_LIST_PRODUCTS_ERROR = 'SET_USER_LIST_PRODUCTS_ERROR';


// PRODUCT
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';