export const countryTranslation = [
  {name: "Abkhazian", code: "ab-AB"},
  {name: "Afar", code: "aa-AA"},
  {name: "Afrikaans", code: "af-ZA"},
  {name: "Akan", code: "ak-AK"},
  {name: "Albanian", code: "sq-AL"},
  {name: "Amharic", code: "am-AM"},
  {name: "Arabic", code: "ar-SA"},
  {name: "Arabic", code: "ar-AE"},
  {name: "Aragonese", code: "an-AN"},
  {name: "Armenian", code: "hy-HY"},
  {name: "Assamese", code: "as-AS"},
  {name: "Avaric", code: "av-AV"},
  {name: "Avestan", code: "ae-AE"},
  {name: "Aymara", code: "ay-AY"},
  {name: "Azerbaijani", code: "az-AZ"},  
  {name: "Bambara", code: "bm-BM"},
  {name: "Bashkir", code: "ba-BA"},  
  {name: "Basque", code: "eu-ES"},
  {name: "Belarusian", code: "be-BY"},
  {name: "Bengali", code: "bn-BD"},
  {name: "Bislama", code: "bi-BI"},
  {name: "Bokmåe, Norwegian; Norwegian Bokmål", code: "nb-NO"},
  {name: "Bosnian", code: "bs-BS"},
  {name: "Breton", code: "br-BR"},
  {name: "Bulgarian", code: "bg-BG"},
  {name: "Burmese", code: "my-MY"},
  {name: "Cantonese", code: "cn-CN"},
  {name: "Catalan; Valencian", code: "ca-ES"},
  {name: "Central Khmer", code: "km-KM}"},
  {name: "Chamorro", code: "ch-GU"},
  {name: "Chechen", code: "ce-CE"},
  {name: "Chichewa; Chewa; Nyanja", code: "ny-NY"},
  {name: "Chinese", code: "zh-CN"},
  {name: "Chinese", code: "zh-HK"},
  {name: "Chinese", code: "zh-SG"},
  {name: "Chinese", code: "zh-TW"},
  {name: "Church Slavic; Old Slavonic; Church Slavonic", code: "cu-CU"},
  {name: "Chuvash", code: "cv-CV"},
  {name: "Cornish", code: "kw-KW"},
  {name: "Corsican", code: "co-CO"},
  {name: "Cree", code: "cr-CR"},
  {name: "Croatian", code: "hr-HR"},
  {name: "Czech", code: "cs-CZ"},
  {name: "Danish", code: "da-DK"},
  {name: "Divehi; Dhivehi; Maldivian", code: "dv-DV"},
  {name: "Dutch; Flemish", code: "nl-NL"},
  {name: "Dutch; Flemish", code: "nl-BE}"},
  {name: "Dzongkha", code: "dz-DZ"},
  {name: "English", code: "en-US"},
  {name: "English", code: "en-AU"},
  {name: "English", code: "en-CA"},
  {name: "English", code: "en-GB"},
  {name: "English", code: "en-IE"},
  {name: "English", code: "en-NZ"},
  {name: "Esperanto", code: "eo-EO"},
  {name: "Estonian", code: "et-EE"},
  {name: "Ewe", code: "ee-EE"},
  {name: "Faroese", code: "fo-FO"},
  {name: "Fijian", code: "fj-FJ"},
  {name: "Finnish", code: "fi-FI"},
  {name: "French", code: "fr-FR"},  
  {name: "French", code: "fr-CA"},  
  {name: "Fulah", code: "ff-FF"},  
  {name: "Gaelic; Scottish Gaelic", code: "gd-GB"},  
  {name: "Galician", code: "gl-ES"},  
  {name: "Ganda", code: "lg-LG"},  
  {name: "Georgian", code: "ka-GE"},  
  {name: "German", code: "de-DE"},  
  {name: "German", code: "de-AT"},  
  {name: "German", code: "de-CH"},  
  {name: "Greek", code: "el-GR"},  
  {name: "Guarani", code: "gn-GN"},  
  {name: "Gujarati", code: "gu-GU"},  
  {name: "Haitian; Haitian Creole", code: "ht-HT"}, 
  {name: "Hausa", code: "ha-HA"},  
  {name: "Hebrew", code: "he-IL"},  
  {name: "Herero", code: "hz-HZ"},  
  {name: "Hindi", code: "hi-IN"},  
  {name: "Hiri Motu", code: "ho-HO"},  
  {name: "Hungarian", code: "hu-HU"},  
  {name: "Icelandic", code: "is-IS"},  
  {name: "Ido", code: "io-IO"},  
  {name: "Igbo", code: "ig-IG"},  
  {name: "Indonesian", code: "id-ID"}, 
  {name: "Interlingua International Auxiliary Language Association", code: "ia-IA"},
  {name: "Interlingue; Occidental", code: "ie-IE"}, 
  {name: "Inuktitut", code: "iu-IU"},  
  {name: "Inupiaq", code: "ik-IK"},  
  {name: "Irish", code: "ga-IE"},  
  {name: "Italian", code: "it-IT"},  
  {name: "Japanese", code: "ja-JP"},  
  {name: "Javanese", code: "jv-JV"},  
  {name: "Kalaallisut; Greenlandic", code: "kl-KL"},  
  {name: "Kannada", code: "kn-IN"},  
  {name: "Kanuri", code: "kr-KR"},  
  {name: "Kashmiri", code: "ks-KS"},  
  {name: "Kazakh", code: "kk-KZ"},  
  {name: "Kikuyu; Gikuyu", code: "ki-KI"},  
  {name: "Kinyarwanda", code: "rw-RW"},  
  {name: "Kirghiz; Kyrgyz", code: "ky-KG"},  
  {name: "Komi", code: "kv-KV"},  
  {name: "Kongo", code: "kg-KG"},  
  {name: "Korean", code: "ko-KR"},  
  {name: "Kuanyama; Kwanyama", code: "kj-KJ"},  
  {name: "Kurdish", code: "ku-KU"},  
  {name: "Lao", code: "lo-LO"},  
  {name: "Latin", code: "la-LA"},  
  {name: "Latvian", code: "lv-LV"},  
  {name: "Limburgan; Limburger; Limburgish", code: "li-LI"},  
  {name: "Lingala", code: "ln-LN"},  
  {name: "Lithuanian", code: "lt-LT"},  
  {name: "Lithuanian", code: "lt-LT"},  
  {name: "Luba-Katanga", code: "lu-LU"},  
  {name: "Luxembourgish; Letzeburgesch", code: "lb-LB"},  
  {name: "Macedonian", code: "mk-MK"},  
  {name: "Malagasy", code: "mg-MG"},  
  {name: "Malay", code: "ms-MY"},  
  {name: "Malay", code: "ms-SG"},  
  {name: "Malayalam", code: "ml-IN"},  
  {name: "Maltese", code: "mt-MT"},  
  {name: "Manx", code: "gv-GV"},  
  {name: "Maori", code: "mi-MI"},  
  {name: "Marathi", code: "mr-IN"},  
  {name: "Marshallese", code: "mh-MH"},  
  {name: "Moldavian; Moldovan", code: "mo-MO"},   
  {name: "Mongolian", code: "mn-MN"},  
  {name: "Nauru", code: "na-NA"},  
  {name: "Navajo; Navaho", code: "nv-NV"},  
  {name: "Ndebele, North; North Ndebele", code: "nd-ND"},  
  {name: "Ndebele, South; South Ndebele", code: "nr-NR"},  
  {name: "Ndonga", code: "ng-NG"},  
  {name: "Nepali", code: "ne-NE"},   
  {name: "Northern Sami", code: "se-SE"},   
  {name: "Norwegian", code: "no-NO"},  
  {name: "Norwegian Nynorsk; Nynorsk, Norwegian", code: "nn-NN"},  
  {name: "Occitan post 1500", code: "oc-OC"}, 
  {name: "Ojibwa", code: "oj-OJ"},  
  {name: "Oriya", code: "or-OR"},  
  {name: "Oromo", code: "om-OM"},  
  {name: "Ossetian; Ossetic", code: "os-OS"},  
  {name: "Pali", code: "pi-PI"},  
  {name: "Panjabi; Punjabi", code: "pa-IN"},  
  {name: "Persian", code: "fa-IR"},  
  {name: "Polish", code: "pl-PL"},  
  {name: "Portuguese", code: "pt-PT"},  
  {name: "Portuguese", code: "pt-BR"},  
  {name: "Pushto; Pashto", code: "ps-PS"},  
  {name: "Quechua", code: "qu-QU"},  
  {name: "Romanian", code: "ro-RO"},  
  {name: "Romansh", code: "rm-RM"},  
  {name: "Rundi", code: "rn-RN"},  
  {name: "Russian", code: "ru-RU"},  
  {name: "Samoan", code: "sm-SM"},  
  {name: "Sango", code: "sg-SG"},  
  {name: "Sanskrit", code: "sa-SA"},  
  {name: "Sardinian", code: "sc-SC"},  
  {name: "Serbian", code: "sr-RS"},  
  {name: "Serbo-Croatian", code: "sh-SH"},  
  {name: "Shona", code: "sn-SN"},  
  {name: "Sichuan Yi; Nuosu", code: "ii-II"},  
  {name: "Sindhi", code: "sd-SD"},  
  {name: "Sinhala; Sinhalese", code: "si-LK"},
  {name: "Slovak", code: "sk-SK"},  
  {name: "Slovenian", code: "sl-SI"},  
  {name: "Somali", code: "so-SO"},  
  {name: "Sotho, Southern", code: "st-ST"},  
  {name: "Spanish; Castilian", code: "es-ES"},  
  {name: "Spanish; Castilian", code: "es-MX"},  
  {name: "Sundanese", code: "su-SU"},  
  {name: "Swahili", code: "sw-SW"},  
  {name: "Swati", code: "ss-SS"},  
  {name: "Swedish", code: "sv-SE"},  
  {name: "Tagalog", code: "tl-PH"},  
  {name: "Tahitian", code: "ty-TY"},
  {name: "Tajik", code: "tg-TG"},
  {name: "Tamil", code: "ta-IN"},
  {name: "Tatar", code: "tt-TT"}, 
  {name: "Telugu", code: "te-IN"},
  {name: "Thai", code: "th-TH"},
  {name: "Tibetan", code: "bo-BO"},
  {name: "Tigrinya", code: "ti-TI"},
  {name: "Tonga Tonga Islands", code: "to-TO"},
  {name: "Tsonga", code: "ts-TS"},
  {name: "Tswana", code: "tn-TN"},
  {name: "Turkish", code: "tr-TR"},
  {name: "Turkmen", code: "tk-TK"},
  {name: "Twi", code: "tw-TW"},
  {name: "Uighur; Uyghur", code: "ug-UG"},
  {name: "Ukrainian", code: "uk-UA"},
  {name: "Urdu", code: "ur-UR"},
  {name: "Uzbek", code: "uz-UZ"},
  {name: "Venda", code: "ve-VE"},
  {name: "Vietnamese", code: "vi-VN"},
  {name: "Volapük", code: "vo-VO"},
  {name: "Walloon", code: "wa-WA"},
  {name: "Welsh", code: "cy-GB"},
  {name: "Western Frisian", code: "fy-FY"},
  {name: "Wolof", code: "wo-WO"},
  {name: "Xhosa", code: "xh-XH"},
  {name: "Yiddish", code: "yi-YI"},
  {name: "Yoruba", code: "yo-YO"},
  {name: "Zhuang; Chuang", code: "za-ZA"},
  {name: "Zulu", code: "zu-ZA"}
]