import Head from "next/head";
import { HowItWorksContainer } from "../src/styles/Pages/howItWorksStyle";
import { TitlePage, CustomMessage } from "../src/atoms";

export default function ProductDetails({}) {
  
  return (
    <HowItWorksContainer>
      <Head>
        <title> How it works | Aperifilm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#e30000" />
        <meta name="msapplication-TileColor" content="#ffc40d" />
        <meta name="theme-color" content="#ffffff"></meta>
      </Head>

      <TitlePage title={"pageTitleHowItWorks"} hasBackButton />

      <CustomMessage text="Work in progress"  style={{marginTop: "20px", fontSize: "16px"}} />

    </HowItWorksContainer>
  );
}
