import Head from "next/head";
import { FormattedMessage } from "react-intl";
import { useSelector } from "react-redux";
import Logo from '../src/assets/images/logo-aperifilm.svg';
import { Image } from "../src/atoms";
import { HomeContainer } from "../src/styles/Pages/style";


//export async function getServerSideProps() {}

export default function Home({}) {
  const user = useSelector((state) => state.userData);
  return (
    <HomeContainer>
      <Head>
        <title>Discover | Aperifilm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#e30000" />
        <meta name="msapplication-TileColor" content="#ffc40d" />
        <meta name="theme-color" content="#ffffff"></meta>
      </Head>

      {user?.email ? (
        <div>
          {user && Object.entries(user).map(([key, value], i) => (
              <p key={i}>{i + 1} - {key}: {value}</p>
            ))}
        </div>
      ) : (
        <div>
          <a href="/api/auth/login">Login</a>
        </div>
      )}
    </HomeContainer>
  );
}
