import Head from "next/head";
import { FormattedMessage } from "react-intl";
import { useSelector } from "react-redux";
import { TitlePage } from "../src/atoms";
import { Container, HomeContainer} from "../src/styles/Pages/homeStyle";
import { useEffect, useState } from "react";
import { RowCard } from "../src/components";
import useMediaQuery from "../src/hooks/useMediaQuery";
import { langConverter, tmdbApiKey } from "../src/js/utility";

export async function getServerSideProps() {
  try {
    const resDiscoverMovie = await fetch('https://api.themoviedb.org/3/discover/movie?api_key=e2330ecaa641a077ab62520c44ab636f&language=it-IT');
    const discoverMovieList = await resDiscoverMovie.json();

    const resComingSoon = await fetch('https://api.themoviedb.org/3/movie/upcoming?api_key=e2330ecaa641a077ab62520c44ab636f&language=it-IT&region=IT');
    const comingSoonMovieList = await resComingSoon.json();

    const resDiscoverTv = await fetch('https://api.themoviedb.org/3/discover/tv?api_key=e2330ecaa641a077ab62520c44ab636f&language=it-IT');
    const discoverTvList = await resDiscoverTv.json();
    
    return {
      props: {
        discoverMovieList,
        comingSoonMovieList,
        discoverTvList
      },
    };
  } catch (err) {
    console.error(err);
    return {
      props: {
        err: "Something went wrong",
      },
    };
  }
}

export default function Home({discoverMovieList, comingSoonMovieList, discoverTvList}) {
  const [welcomeVisible, setWelcomeVisible] = useState(true);
  const [discoverMovieListState, setDiscoverMovieListState] = useState([]);
  const [comingSoonMovieListState, setComingSoonListState] = useState([]);
  const [discoverTvListState, setDiscoverTvListState] = useState([]);
  const user = useSelector((state) => state.userData);
  const userLanguageState = useSelector((state) => state.userData.language);

  const isTablet = useMediaQuery(769);

  const getComingSoonByRegion = async () => {
    // setIsLoaded(false);
    if (userLanguageState) {
      const coming = await fetch(
        `https://api.themoviedb.org/3/movie/upcoming?api_key=${tmdbApiKey}&language=it-IT&region=${userLanguageState === 'it' ? 'IT' : 'US'}`
        ).then(res => res.json());
      setComingSoonListState(coming?.results.slice(0, 4));
    }
  };

  useEffect(() => {
    getComingSoonByRegion();
  }, [userLanguageState]);

  useEffect(() => {
    setDiscoverMovieListState(discoverMovieList?.results.slice(0, 2));
    setComingSoonListState(comingSoonMovieList?.results.slice(0, 4));
    setDiscoverTvListState(discoverTvList?.results.slice(0, 2));
  }, [discoverMovieList, comingSoonMovieList])

  console.log('DISCOVER TV: ', discoverTvList);
  return (
    <HomeContainer>
      <Head>
        <title>Discover | Aperifilm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#e30000" />
        <meta name="msapplication-TileColor" content="#ffc40d" />
        <meta name="theme-color" content="#ffffff"></meta>
      </Head>

      {user?.email && (
        <Container>
          {user && Object.entries(user).map(([key, value], i) => {
            if (key !== 'list_products' && key !== 'favorite' && key !== 'voted' && key !== 'towatch') {
              return (
                <p key={i}>{i + 1} - {key}: {value}</p>
              )
            } 
            })}

            {user?.favorite && (
              <>
                <p><FormattedMessage defaultMessage={"menuLinkTitleFavorite"} id={"menuLinkTitleFavorite"} /></p>
                {user.favorite.map((elm, index) => (
                  <p key={index}>{elm.title}</p>
                ))}
              </>
            )}

            {user?.voted && (
              <>
                <p><FormattedMessage defaultMessage={"menuLinkTitleVoted"} id={"menuLinkTitleVoted"} /></p>
                {user.voted.map((elm, index) => (
                  <p key={index}>{elm.title}</p>
                ))}
              </>
            )}

            {user?.towatch && (
              <>
                <p><FormattedMessage defaultMessage={"menuLinkTitleToWatch"} id={"menuLinkTitleToWatch"} /></p>
                {user.towatch.map((elm, index) => (
                  <p key={index}>{elm.title}</p>
                ))}
              </>
            )}
            
        </Container>
      )}

      <TitlePage title="menuLinkTitleDiscover" />

      {/* Discover FILM */}
      <RowCard 
        listProducts={discoverMovieListState}
        type="discover"
        productType="productTypeFilm"
        goToText="goToDiscoverNewFilm"
      />

      {/* COMING SOON */}
      <RowCard 
        listProducts={comingSoonMovieListState}
        type="default"
        title="sectionTitleComingOutFilm"
        productType="productTypeFilm"
        goToText="goToPage"
      />
      {/* <Row>
        <RowHeader>
          <Montserrat className="card-title" type="bold" configuration={{fontSize: isTablet ? 20 : 24, fontWeight: 600, lineHeight: "17.07px", color: theme.colors.element.light}}><FormattedMessage defaultMessage="sectionTitleComingOutFilm" id="sectionTitleComingOutFilm" /></Montserrat>

          {!isTablet && (
            <GoTo handleOnClick={() => onClose()} url="/search-results">
              <Icon 
                stroke={theme.colors.mainBrandColors.dark}
                width="18px"
                height="17px"
              >
                <ArrowNarrowRightIcon />
              </Icon>
            </GoTo>
          )}				
        </RowHeader>
        <RowCards type="default">
          <Card className="card" type="default"/>
          <Card className="card" type="default"/>
          <Card className="card" type="default"/>
          <Card className="card" type="default"/>
        </RowCards>
        {isTablet && (
          <GoTo className="goto-rowcard-mobile" handleOnClick={() => onClose()} url="/search-results">
            <Icon 
              stroke={theme.colors.mainBrandColors.dark}
              width="18px"
              height="17px"
            >
              <ArrowNarrowRightIcon />
            </Icon>
          </GoTo>
          )}
      </Row> */}

      {/* POPULAR PEOPLE */}
      {/* <Row>
        <RowHeader>
          <Montserrat className="card-title" type="bold" configuration={{fontSize: isTablet ? 20 : 24, fontWeight: 600, lineHeight: "17.07px", color: theme.colors.element.light}}><FormattedMessage defaultMessage="sectionTitlePopularPeople" id="sectionTitlePopularPeople" /></Montserrat>

          {!isTablet && (
            <GoTo handleOnClick={() => onClose()} url="/search-results">
              <Icon 
                stroke={theme.colors.mainBrandColors.dark}
                width="18px"
                height="17px"
              >
                <ArrowNarrowRightIcon />
              </Icon>
            </GoTo>
          )}				
        </RowHeader>
        <RowCards>
          <Card className="card" type="person" />
          <Card className="card" type="person" />
          <Card className="card" type="person" />
          <Card className="card" type="person" />
          <Card className="card" type="person" />
        </RowCards>
        {isTablet && (
          <GoTo className="goto-rowcard-mobile" handleOnClick={() => onClose()} url="/search-results">
            <Icon 
              stroke={theme.colors.mainBrandColors.dark}
              width="18px"
              height="17px"
            >
              <ArrowNarrowRightIcon />
            </Icon>
          </GoTo>
          )}
      </Row> */}

      {/* DISCOVER SERIE TV */}
      <RowCard 
        listProducts={discoverTvListState}
        type="discover"
        productType="productTypeTvSeries"
        goToText="goToDiscoverNewTvSeries"
      />
      {/* <Row>
        <RowCards type="discover">
          <Card className="card" type="discover" />
          <Card className="card" type="discover" />
        </RowCards>
        <GoTo fontSize="16px" text="goToDiscoverNewTvSeries" className="goto-rowcard" handleOnClick={() => onClose()} url="/search-results">
          <Icon
            fill={theme.colors.mainBrandColors.dark}
            strokeWidth={0}
            width="20px"
            height="20px"
          >
            <FireIcon />
          </Icon>
        </GoTo>
      </Row> */}

      {/* POPULAR SERIE TV */}
      {/* <Row>
        <RowHeader>
          <Montserrat className="card-title" type="bold" configuration={{fontSize: isTablet ? 20 : 24, fontWeight: 600, lineHeight: "17.07px", color: theme.colors.element.light}}><FormattedMessage defaultMessage="sectionTitlePopularTvSeries" id="sectionTitlePopularTvSeries" /></Montserrat>

          {!isTablet && (
            <GoTo handleOnClick={() => onClose()} url="/search-results">
              <Icon 
                stroke={theme.colors.mainBrandColors.dark}
                width="18px"
                height="17px"
              >
                <ArrowNarrowRightIcon />
              </Icon>
            </GoTo>
          )}				
        </RowHeader>
        <RowCards type="default">
          <Card className="card" type="default"/>
          <Card className="card" type="default"/>
          <Card className="card" type="default"/>
          <Card className="card" type="default"/>
        </RowCards>
        {isTablet && (
          <GoTo className="goto-rowcard-mobile" handleOnClick={() => onClose()} url="/search-results">
            <Icon 
              stroke={theme.colors.mainBrandColors.dark}
              width="18px"
              height="17px"
            >
              <ArrowNarrowRightIcon />
            </Icon>
          </GoTo>
          )}
      </Row> */}
    </HomeContainer>
  );
}
